openapi: 3.1.0
info:
  title: Hello World API
  version: 1.0.0
servers:
  - url: https://apimocks.free.beeceptor.com
paths:
  /hello:
    get:
      summary: Returns a greeting
      responses:
        '200':
          description: Successful response
          content:
            text/plain:
              schema: 
                type: string
                example: Hello, world!
components:
  securitySchemes:
    OAuth2:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: https://dev-xerurkzp.us.auth0.com/oauth/token
          scopes:
            read:hello: Read access to the hello endpoint
security:
  - OAuth2:
      - read:hello